In [29]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import lightgbm as lgb

# Importing the dataset
dataset = pd.read_csv('./train_50k.csv')

FEATURE_SIZE=5
X = dataset.iloc[:,0:FEATURE_SIZE].values
y = dataset.iloc[:, FEATURE_SIZE].values

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(X, y, test_size = 0.2, random_state = 0)
x_val, x_test, y_val, y_test = train_test_split(x_val, y_val, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
x_val=sc.transform(x_val)



In [30]:
dataset.iloc[:,0:FEATURE_SIZE]

CN        RA        JC        AA         PA
0       6  0.002123  0.000259  0.708881   393567.0
1       6  0.000457  0.000083  0.591653   863352.0
2      31  0.001395  0.000517  2.948132  2156976.0
3      15  0.001420  0.003846  1.498468   200876.0
4       7  0.000231  0.000261  0.665988   428192.0
...    ..       ...       ...       ...        ...
99995   0  0.000000  0.000000  0.000000       14.0
99996   0  0.000000  0.000000  0.000000        2.0
99997   0  0.000000  0.000000  0.000000        1.0
99998   0  0.000000  0.000000  0.000000        3.0
99999   0  0.000000  0.000000  0.000000        2.0

[100000 rows x 5 columns]

In [31]:
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier()

In [32]:
y_train

array([1., 0., 1., ..., 1., 1., 0.])

In [33]:
clf.fit(x_train, y_train)




#Prediction
y_pred=clf.predict(x_test)
#convert into binary values
for i in range(len(y_pred)):
    if y_pred[i]>=.5:       # setting threshold to .5
        y_pred[i]=1
    else:
        y_pred[i]=0
    
#Accuracy
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred,y_test)
print(accuracy)

# AUC
from sklearn.metrics import roc_auc_score
print(roc_auc_score(y_test, y_pred))




ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [26]:
testdata = pd.read_csv('test.csv')
x_testing = testdata.iloc[:,0:FEATURE_SIZE].values
x_testing = sc.transform(x_testing)
y_pred=clf.predict_proba(x_testing)[:,1]

In [27]:
import csv
with open("kaggle_adaboost.csv","w",newline="") as csvfile:
    writer=csv.writer(csvfile)
    writer.writerow(["Id","Predicted"])
    test_id=1
    for prediction in y_pred:
        writer.writerow([test_id,prediction])
        test_id+=1

In [28]:
# 76 % Submission on Kaggle with random sampling

array([0, 0, 1, ..., 0, 0, 0])

array([1, 0, 0, ..., 1, 1, 0])